import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: { tsconfig: 'tsconfig.build.json' },
  tsconfig: 'tsconfig.build.json',
  splitting: true,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    '@mhersztowski/core',
    'monaco-editor',
    '@mui/material',
    '@mui/icons-material',
    '@mui/x-tree-view',
    '@emotion/react',
    '@emotion/styled',
    '@xterm/xterm',
    '@xterm/xterm/css/xterm.css',
    '@xterm/addon-fit',
    'blockly',
    'blockly/javascript',
    '@xyflow/react',
    '@xyflow/react/dist/style.css',
    'highlight.js/styles/github-dark.css',
    'katex/dist/katex.min.css',
    'unified',
    'remark-breaks',
    'remark-gfm',
    'remark-math',
    'remark-parse',
    'remark-rehype',
    'rehype-highlight',
    'rehype-katex',
    'rehype-raw',
    'rehype-react',
    'rehype-slug',
  ],
  treeshake: true,
});
