export type AppSessionPlatform = 'web' | 'mobile' | 'desktop';

/**
 * Identifies the page/project the user is currently working on.
 * Sent in every heartbeat; backend accumulates time per context.
 */
export interface AppSessionContext {
  /** Category: 'arduino' | 'upython' | 'pygame' | 'iot-device' | 'notes' | 'pim' | ... */
  type: string;
  /** Project or resource ID within the category (if applicable) */
  id?: string;
}

/** Aggregated time spent on a context (project/section) across all sessions */
export interface ProjectTimeStat {
  userId: string;
  contextType: string;
  contextId: string;
  totalSeconds: number;
  activeSeconds: number;
  lastSeenAt: number;
  /** Per-day breakdown for the last 7 days */
  days: AppSessionDayStat[];
}

export interface AppSession {
  /** Unique session ID (UUID, generated by the client) */
  id: string;
  /** Owning user */
  userId: string;
  /** Human-readable label: browser + OS or "Desktop Agent" */
  label: string;
  platform: AppSessionPlatform;
  /** Raw User-Agent string (web/mobile) or OS description (desktop) */
  userAgent: string;
  /** Unix ms — when the hello was first received */
  startedAt: number;
  /** Unix ms — last heartbeat received */
  lastSeenAt: number;
  /** Cumulative seconds the app was open */
  totalSeconds: number;
  /** Cumulative seconds the user was actively interacting (mouse/keyboard/touch) */
  activeSeconds: number;
}

/** Per-day bucket for weekly aggregation */
export interface AppSessionDayStat {
  /** ISO date string YYYY-MM-DD */
  date: string;
  totalSeconds: number;
  activeSeconds: number;
}

export interface AppSessionWeekStats {
  sessionId: string;
  userId: string;
  platform: AppSessionPlatform;
  label: string;
  days: AppSessionDayStat[];
}
