/** Auto-generated by `pnpm gen:api` — do not edit by hand.
 *  Self-contained type bundle for `ProjectData`. */

export type Units = 'mm' | 'cm' | 'm' | 'in';

export interface ProjectSettings {
  name: string;
  units: Units;
  gridSize: number;
  precision: number;
}

export type LineType = 'solid' | 'dashed' | 'dotted' | 'dashdot';

export interface Layer {
  id: string;
  name: string;
  color: string;
  lineType: LineType;
  lineWidth: number;
  visible: boolean;
  locked: boolean;
}

export type EntityType = 'line' | 'circle' | 'polyline' | 'rect' | 'arc' | 'ellipse' | 'point' | 'text' | 'image' | 'dimension' | 'box3d' | 'cylinder3d' | 'sphere3d' | 'freehand';

export interface BoundingBox2D {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface EntityBase {
  id: string;
  type: EntityType;
  layerId: string;
  color: string | 'bylayer';
  lineType: LineType | 'bylayer';
  lineWidth: number | 'bylayer';
  visible: boolean;
  locked: boolean;
  extrudeHeight: number; // 0 = flat 2D
  boundingBox: BoundingBox2D;
}

export interface LineEntity extends EntityBase {
  type: 'line';
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface CircleEntity extends EntityBase {
  type: 'circle';
  cx: number;
  cy: number;
  radius: number;
}

export interface Point2D {
  x: number;
  y: number;
}

export interface PolylineEntity extends EntityBase {
  type: 'polyline';
  points: Point2D[];
  closed: boolean;
}

export interface RectEntity extends EntityBase {
  type: 'rect';
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ArcEntity extends EntityBase {
  type: 'arc';
  cx: number;
  cy: number;
  radius: number;
  startAngle: number; // radians
  endAngle: number;   // radians
}

export interface TextEntity extends EntityBase {
  type: 'text';
  x: number;
  y: number;
  content: string;
  fontSize: number;   // world units
  fontFamily: string;
  angle: number;      // radians
}

export interface ImageEntity extends EntityBase {
  type: 'image';
  x: number;          // bottom-left
  y: number;
  width: number;
  height: number;
  src: string;        // data URL or external URL
}

export interface FreehandEntity extends EntityBase {
  type: 'freehand';
  points: Point2D[];
  strokeWidth: number;
  smooth: boolean;
}

export interface DimAnchor {
  entityId: string;
  kind: 'endpoint' | 'midpoint' | 'center' | 'point-on';
  /** endpoint/midpoint index, or polyline segment, or rect edge (0..3). */
  index?: number;
  /** parameter [0..1] along a segment/edge (point-on line/polyline/rect). */
  t?: number;
  /** radians on a circle/arc (point-on circle/arc). */
  angle?: number;
  /** When true the anchor is kept but ignored — the endpoint behaves as a literal point. */
  disabled?: boolean;
}

export interface DimensionEntity extends EntityBase {
  type: 'dimension';
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  offset: number; // signed perpendicular distance from p1-p2 line to dimension line
  /** When set, x1,y1 are resolved live from this anchor (follows the shape). */
  anchor1?: DimAnchor;
  /** When set, x2,y2 are resolved live from this anchor (follows the shape). */
  anchor2?: DimAnchor;
}

export interface Box3dEntity extends EntityBase {
  type: 'box3d';
  cx: number;  // center X
  cy: number;  // center Y
  width: number;
  depth: number;   // Y dimension (footprint depth)
  height: number;  // Z extrusion height
}

export interface Cylinder3dEntity extends EntityBase {
  type: 'cylinder3d';
  cx: number;
  cy: number;
  radius: number;
  height: number;  // Z extrusion height
}

export interface Sphere3dEntity extends EntityBase {
  type: 'sphere3d';
  cx: number;
  cy: number;
  radius: number;
}

export type Entity =
  | LineEntity
  | CircleEntity
  | PolylineEntity
  | RectEntity
  | ArcEntity
  | TextEntity
  | ImageEntity
  | FreehandEntity
  | DimensionEntity
  | Box3dEntity
  | Cylinder3dEntity
  | Sphere3dEntity;

export interface ProjectData {
  version: string;
  settings: ProjectSettings;
  layers: { layers: Layer[]; activeId: string };
  entities: Entity[];
}
