/** Auto-generated by `pnpm gen:api` — do not edit by hand.
 *  Self-contained type bundle for `EventModel`. */

export interface EventComponentModel {
    type: string;
}

export interface EventModel {
    type: "event";
    taskId?: string;
    name: string;
    description?: string;
    startTime: string;
    endTime?: string;
    components?: EventComponentModel[];
}
