/** Auto-generated by `pnpm gen:api` — do not edit by hand.
 *  Self-contained type bundle for `PersonModel`. */

export interface PersonModel {
    type: "person";
    id: string;
    nick: string;
    firstName?: string;
    secondName?: string;
    description?: string;
}
