/** Auto-generated by `pnpm gen:api` — do not edit by hand.
 *  Self-contained type bundle for `ProjectModel`. */

export interface TaskComponentModel {
    type: string;
}

export interface TaskModel {
    type: "task";
    id: string;
    projectId?: string;
    name: string;
    description?: string;
    duration?: number;
    cost?: number;
    components?: TaskComponentModel[];
}

export interface ProjectComponentModel {
    type: string;
}

export interface ProjectModel {
    type: "project";
    id: string;
    name: string;
    description?: string;
    cost?: number;
    projects?: ProjectModel[];
    tasks?: TaskModel[];
    components?: ProjectComponentModel[];
}
