/** Auto-generated by `pnpm gen:api` — do not edit by hand.
 *  Self-contained type bundle for `TaskModel`. */

export interface TaskComponentModel {
    type: string;
}

export interface TaskModel {
    type: "task";
    id: string;
    projectId?: string;
    name: string;
    description?: string;
    duration?: number;
    cost?: number;
    components?: TaskComponentModel[];
}
