import type { UPythonBoardManager } from '../boards/BoardManager';
import { registerEventBlocks } from './event';
import { registerPinBlocks, registerPinV2Blocks } from './pin';
import { registerAdcBlocks, registerAdcV2Blocks } from './adc';
import { registerPwmBlocks, registerPwmV2Blocks } from './pwm';
import { registerTimeBlocks } from './time';
import { registerTimerBlocks, registerTimerV2Blocks } from './timer';
import { registerDisplayBlocks } from './display';
import { registerUartBlocks, registerUartV2Blocks } from './uart';
import { registerI2cBlocks, registerI2cV2Blocks } from './i2c';
import { registerSpeakerBlocks } from './speaker';
import { registerWifiBlocks } from './wifi';
import { registerBitsBlocks } from './bits';
import { registerTypeConvBlocks } from './typeconv';
import { registerControlBlocks } from './control';
import { registerMathBlocks } from './math';
import { registerTextBlocks } from './text';
import { registerListBlocks } from './lists';
import { registerTupleBlocks } from './tuples';
import { registerMapBlocks } from './maps';
import { registerJsonBlocks } from './json';
import { registerBytearrayBlocks } from './bytearray';
import { registerBytesBlocks } from './bytes';
import { registerSdcardBlocks } from './sdcard';
import { registerCanBlocks } from './can';
import { registerI2sBlocks } from './i2s';
import { registerSpiV2Blocks } from './spi_v2';
import { registerWdtBlocks } from './wdt';
import { registerRtcBlocks } from './rtc';
import { registerButtonBlocks } from './button';
import { registerRgbIrBlocks } from './rgb_ir';

export function registerAllBlocks(boardManager: UPythonBoardManager): void {
  registerEventBlocks();
  registerPinBlocks(boardManager);
  registerPinV2Blocks();
  registerAdcBlocks(boardManager);
  registerAdcV2Blocks();
  registerPwmBlocks(boardManager);
  registerPwmV2Blocks();
  registerTimeBlocks();
  registerTimerBlocks();
  registerTimerV2Blocks();
  registerDisplayBlocks();
  registerUartBlocks(boardManager);
  registerUartV2Blocks();
  registerI2cBlocks(boardManager);
  registerI2cV2Blocks();
  registerSpeakerBlocks();
  registerWifiBlocks();
  registerBitsBlocks();
  registerTypeConvBlocks();
  registerControlBlocks();
  registerMathBlocks();
  registerTextBlocks();
  registerListBlocks();
  registerTupleBlocks();
  registerMapBlocks();
  registerJsonBlocks();
  registerBytearrayBlocks();
  registerBytesBlocks();
  registerSdcardBlocks();
  registerCanBlocks();
  registerI2sBlocks();
  registerSpiV2Blocks();
  registerWdtBlocks();
  registerRtcBlocks();
  registerButtonBlocks();
  registerRgbIrBlocks();
}
